spring:
  application:
    name: WebDuLich

  datasource:
    url: jdbc:mysql://mysql-67a2666-daokecuong13091974-d15a.d.aivencloud.com:26574/web_du_lich?sslMode=REQUIRED
    username: avnadmin
    password: AVNS_8auRZXjM6yC11qDhWPs
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
jwt:
  signerKey: 6S6MJ2VCGhbsMvq4XQiNEO6VF5+UtMJP3OwldQR5UoTEj9Ej6nBG/8CWvDsaIdbt